Sample problem of predicting home price in monroe, new jersey (USA)

Below is the table containing home prices in monroe twp, NJ. Here price depends on area (square feet), bed rooms and age of the home (in years). Given these prices we have to predict prices of new homes based on area, bed rooms and age.

Given these home prices find out price of a home that has,

3000 sqr ft area, 3 bedrooms, 40 year old

2500 sqr ft area, 4 bedrooms, 5 year old

We will use regression with multiple variables here. Price can be calculated using following equation,

price = m1*area + m2*bedrooms + m3*age + b
simplified as
y = m1x1 + m2x2 + m3x3 + b



In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv(r'D:\Machine Learning\py-master\py-master\ML\1_linear_reg\homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000
5  4100       6.0    8  810000

Data Preprocessing: Fill NA values with median value of a column

In [4]:
df.bedrooms.median()

4.0

In [6]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000
5  4100       6.0    8  810000

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [8]:
reg.coef_

array([  114.65890296, 53376.41887759,  4767.23988188])

In [9]:
reg.intercept_

-36145.78849189251

Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [10]:
reg.predict([[3000, 3, 40]])

array([658649.77229988])

In [11]:
114.65890296*3000+53376.41887759*3+4767.23988188*40-36145.78849189251

658649.7722960775

Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [12]:
reg.predict([[2500, 4, 5]])

array([487843.34383095])